name: Build and Deploy Resume PDF

on:
  push:
    paths:
      - '.private/Sandesh_Sawane_Resume.tex'
  pull_request:
    paths:
      - '.private/Sandesh_Sawane_Resume.tex'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: .private/Sandesh_Sawane_Resume.tex
      
      - name: Generate Preview Image
        run: |
                sudo apt-get install -y poppler-utils
                pdftoppm -png -r 150 -f 1 -l 1 .private/Sandesh_Sawane_Resume.pdf resume-preview
      - name: Commit and push compiled PDF
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv .private/Sandesh_Sawane_Resume.pdf resume.pdf
          git add resume.pdf resume-preview-1.png
          git commit -m "Auto-compile resume.pdf [skip ci]" || echo "No changes to commit"
          git push
